scan_period: 3

single_tracker: false

mqtt:
  name: BLE Tracker - Livingroom
  host: mqtt.mynetwork.local
  port: 1883
  username: #mqtt-user
  password: #mqtt-pass
  topic: bletracker/livingroom
  qos: 0
  keepalive: 60

messages:
  include_location: false
  include_rssi: true

devices:
  - mac: ca:fe:ca:fe:ca:fe
    name: ble tag 1
    measured_power: -70.7024
    n: 2.01292389
    min_rssi: -79
    timeout: 0
    status_off: not_home
    
  - mac: ca:fe:ca:fe:ca:fd
    name: headset
    subtopic: headset
    min_rssi: -80

#locations:
#  bedroom:
#    min_dist: 0
#    max_dist: 5
#
#  bathroom:
#    min_dist: 5
#    max_dist: 7
#
#  livingroom:
#    min_dist: 7
#    max_dist: 10
