scan_period: 3

single_tracker: true

mqtt:
  name: BLE Tracker
  host: mqtt.mynetwork.local
  port: 1883
  username: #mqtt-user
  password: #mqtt-pass
  topic: bletracker
  qos: 0
  keepalive: 60

messages:
  include_location: false
  include_rssi: false

devices:
  - mac: ca:fe:ca:fe:ca:fe
    name: ble tag 1
    measured_power: -70.7024
    n: 2.01292389
    timeout: 0
    status_off: not_home

  - mac: 00:00:00:00:00:01
    name: ble tag 2
    measured_power: -57.75963
    n: 2.24049349
    timeout: 0
    status_off: not_home

locations:
  bedroom:
    min_dist: 0
    max_dist: 5

  bathroom:
    min_dist: 5
    max_dist: 7

  livingroom:
    min_dist: 7
    max_dist: 10
